name: Weekly Time Reports

on:
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight on Sundays
  workflow_dispatch:      # Allow manual triggering

jobs:
  generate-time-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install axios date-fns fs-extra
        
      - name: Generate time report
        run: node .github/scripts/generate-time-report.js
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          
      - name: Store report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: time-report
          path: ./time-reports/
